Resnet
Xilinx/mlir-aie pull request #1008
Opened 2024-02-11 16:50 UTC by singagan

PR for layer fused ResNet design.

2024-02-11 18:13 UTC, makslevental commented
There are still no tests here - this is unmaintanble code that will be broken within the span of ~1 week in surprising/confusing/uninterpretable ways for users. I'm not going to block but I am urging you to actually add tests so that the code is tested in CI and thus actively maintained.

@stephenneuendorffer

2024-02-11 18:22 UTC, makslevental requested changes

2024-02-11 18:22 UTC, makslevental commented on reference_designs/ipu-xrt/resnet/notebook/.ipynb_checkpoints/bottleneck_init_cifar-checkpoint.ipynb
This is a build artifact - it needs to be removed.

2024-02-12 05:15 UTC, stephenneuendorffer commented
It's great that you're getting this working, but please add suitable tests.

2024-04-18 21:08 UTC, closed without merging