[aie2xclbin] Options to configure pass managers for debug support
Xilinx/mlir-aie pull request #1058
Opened 2024-02-26 23:30 UTC by newling

This PR adds command line options: 

print-ir-before-all
print-ir-after-all
print-ir-module-scope
disable-threading

to aie2xclbin. 

Motivation: When running via iree-amd-aie, failures in aie2xclbin don't provide much in the way of diagnostics. If this lands, I will extend iree-amd-aie's call to aie2xclbin to optionally dump IR.

2024-02-27 23:55 UTC, stephenneuendorffer approved these changes

2024-02-27 23:55 UTC, stephenneuendorffer commented on tools/aie2xclbin/XCLBinGen.cpp
> +  std::function<bool(Pass *, Operation *)> shouldPrintBeforePass =
auto?

2024-02-28 17:26 UTC, spaceotter requested changes

2024-02-28 17:26 UTC, spaceotter commented on tools/aie2xclbin/aie2xclbin.cpp
> +  TK.PrintIRBeforeAll = PrintIRBeforeAll;
You don't set the module scope here.

2024-02-28 21:26 UTC, newling commented on tools/aie2xclbin/aie2xclbin.cpp
> +  TK.PrintIRBeforeAll = PrintIRBeforeAll;
Oof thanks.

2024-02-28 22:02 UTC, spaceotter approved these changes

2024-02-29 19:02 UTC, merged