[Request For Comment] This seems to unbreak my build.
Xilinx/mlir-aie pull request #1095
Opened 2024-03-06 00:22 UTC by newling

Without this change I get:

```
CMake Error at tools/bootgen/CMakeLists.txt:147 (add_executable):
  Target "bootgen" links to target "OpenSSL::applink" but the target was not
  found.  Perhaps a find_package() call is missing for an IMPORTED target, or
  an ALIAS target is missing?
  ```
  when I run 
  
  ```
  ./utils/build-mlir-aie.sh llvm/build
  ```
  
 I don't know what bootgen, or "applink" is.

2024-03-06 00:44 UTC, makslevental commented
No shot this is getting merged lol - these are both components/pieces necessary for assembling xclbins (and it was all introduced as a direct dep in this PR https://github.com/Xilinx/mlir-aie/pull/1060 and then fixed up in this PR https://github.com/Xilinx/mlir-aie/pull/1068). @erieaton-amd can relay all of the details.

2024-03-06 00:45 UTC, makslevental requested changes
.

2024-03-06 00:52 UTC, makslevental commented
I guess there is something fishy if the tests pass? `OpenSSL::applink` is a component of openssl that is required by bootgen because [...reasons...](https://github.com/Xilinx/bootgen/blob/65ed60ae22dbd540a2a480a40732b2c5c1d5eab7/main.cpp#L39)? When we were fighting this last week, that was one of the failures on windows build.

2024-03-06 01:25 UTC, newling commented
How about I make it a dependency (in cmake) only for windows builds?

I guess I could find out why my linux setup doesn't like this when clearly the linux CI doesn't mind it. I am pretty sure I've apt installed all the openssl things available.

2024-03-06 03:03 UTC, makslevental commented
> How about I make it a dependency (in cmake) only for windows builds?
> 
> I guess I could find out why my linux setup doesn't like this when clearly the linux CI doesn't mind it. I am pretty sure I've apt installed all the openssl things available.

you can surround things in CMake with `if(WIN32)` or something like that.

> I am pretty sure I've apt installed all the openssl things available.

You sure you installed `libssl-dev` and not `openssl`? You need the former.

2024-03-06 19:58 UTC, newling commented
> > How about I make it a dependency (in cmake) only for windows builds?
> > I guess I could find out why my linux setup doesn't like this when clearly the linux CI doesn't mind it. I am pretty sure I've apt installed all the openssl things available.
> 
> you can surround things in CMake with `if(WIN32)` or something like that.
> 
> > I am pretty sure I've apt installed all the openssl things available.
> 
> You sure you installed `libssl-dev` and not `openssl`? You need the former.

Yes, libssl-dev, sorry I mistyped.. `libssl-dev is already the newest version (3.0.2-0ubuntu1.12). 0 upgraded, 0 newly installed, 0 to remove and 11 not upgraded`.

Ok cool, I'll play around in CMake if I can't resolve this locally.

2024-03-06 22:47 UTC, makslevental commented
Late breaking developments in the case: https://github.com/Xilinx/mlir-aie/pull/1100#issuecomment-1981910376

2024-03-07 13:36 UTC, makslevental commented
Just aggregating info: https://github.com/openssl/openssl/issues/17767#issuecomment-1050607089

@newling can you double check what version of CMake you're using when you build?

2024-03-07 23:07 UTC, newling commented
I am using
$ which cmake # /usr/bin/cmake
$ cmake --version # cmake version 3.22.1

2024-03-07 23:45 UTC, newling commented
lol yes, bingo indeed. Updating cmake is an easy fix. A cmake conditional might save someone in the future. If I have some time I will do this. 

Thank you for investigating and connecting dots !

2024-03-07 23:51 UTC, makslevental commented
> lol yes, bingo indeed. Updating cmake is an easy fix. A cmake conditional might save someone in the future. If I have some time I will do this.

Fantastic idea - just bump the minimum CMake version here https://github.com/Xilinx/mlir-aie/blob/main/CMakeLists.txt#L16 to `3.23`.

2024-03-08 18:07 UTC, makslevental commented
Did upgrading CMake not work? I would prefer to gate like that if that's the root cause (otherwise sure we can land this and kick the can down the road...)

2024-03-08 19:00 UTC, newling commented
@makslevental  I missed your suggestion before adding the win32 conditional approach. Increasing the minimum required cmake works fine (as it better long term).

2024-03-08 19:00 UTC, makslevental approved these changes

2024-03-08 19:41 UTC, merged