Added AIECreateLogicalLocks
Xilinx/mlir-aie pull request #112
Opened 2022-06-21 06:46 UTC by iavssw

This pass aims to assign lockIDs to AIE.lock operations. The lockID is numbered from the most recent AIE.lock within the same tile. If the lockID exceeds 15 then the pass generates an error and terminates. AIE.lock operations for different tiles are numbered independently. If there exists an existing lockID this pass overwrites the existing lockID generating a warning.

2022-06-27 04:12 UTC, stephenneuendorffer requested changes

2022-06-27 04:12 UTC, stephenneuendorffer commented on include/aie/AIE.td
> +        //Confined<I32Attr, [IntMinValue<0>, IntMaxValue<15>]>:$lockID
Remove comment

2022-06-27 04:12 UTC, stephenneuendorffer commented on include/aie/AIE.td
> +  //let assemblyFormat = [{ `(` $tile `,` $lockID `)` attr-dict }];
comment

2022-06-27 04:12 UTC, stephenneuendorffer commented on include/aie/AIEPasses.td
> +    Generates the absolute lock location numbers.
Can you add an example of what the IR looks like before and after?

2022-06-27 04:12 UTC, stephenneuendorffer commented on include/aie/AIE.td
> +        llvm::errs() << "Lock has no ID value\n";
This should give you a warning about not returning a value.  Probably this should assert, at least?

2022-06-27 04:12 UTC, stephenneuendorffer commented on include/aie/AIEPasses.td
> +def AIECreateLogicalLocks : Pass<"aie-create-logical-locks", "ModuleOp"> {
How about "aie-assign-locks" or "aie-assign-lock-ids"?

2022-06-27 04:12 UTC, stephenneuendorffer commented on lib/AIECreateLogicalLocks.cpp
> +//===- AIEAssignBuffers.cpp -------------------------------------*- C++ -*-===//
wrong name.

2022-06-27 04:12 UTC, stephenneuendorffer commented on lib/AIECreateLogicalLocks.cpp
> +// (c) Copyright 2019 Xilinx Inc.
copyright 2022?

2022-06-27 04:12 UTC, stephenneuendorffer commented on lib/AIECreateLogicalLocks.cpp
> +// existing lockID this pass overwrites the existing lockID generating a
I think if there are existing lock IDs, this pass should be idempotent and not change anything.  (i.e., it should only assign lock ids to locks without an ID.)

2022-06-27 04:12 UTC, stephenneuendorffer commented on lib/AIECreateLogicalLocks.cpp
> +    std::map<Operation *, int> unique_tiles;
maybe "tileToLastID"?  This gives a little bit more information about what the Operation * is pointing to.

2022-06-27 04:12 UTC, stephenneuendorffer commented on test/create-logical-locks/logicallocks.mlir
> +// CHECK:    }
For the purposes of this test, the useLock operations are irrelevent, I think?  If so, it's usually good practice to reduce the size of the test to the absolute minimum.  Also, there are some behaviors you haven't tested (like what happens when there are already lock ids).

2022-07-07 05:15 UTC, iavssw commented
An implementation of a two pass assignLockIDs pass which is idempotent to existing lockIDs.

2022-08-05 19:59 UTC, stephenneuendorffer approved these changes
Looks reasonable.

2022-08-05 20:00 UTC, stephenneuendorffer commented
@iavssw Can you rebase your patch so it can be merged?

2022-08-09 16:10 UTC, iavssw commented
@stephenneuendorffer Rebased

2022-08-09 16:10 UTC, iavssw commented
Rebased

2022-08-11 23:03 UTC, merged