Moved test_utils.py to utils/test.py
Xilinx/mlir-aie pull request #1270
Opened 2024-04-16 21:17 UTC by jackl-xilinx

2024-04-16 21:57 UTC, fifield requested changes

2024-04-16 21:57 UTC, fifield commented on python/utils/ml.py
needs license/copyright

2024-04-16 21:57 UTC, fifield commented on python/utils/test.py
> +# SPDX-License-Identifier: MIT
Should be Apache, not MIT

2024-04-16 21:57 UTC, fifield commented on python/utils/xrt.py
needs license/copyright

2024-04-16 21:57 UTC, fifield commented on python/utils/xrt.py
> +# from npu.runtime
needs license/copyright

2024-04-17 15:42 UTC, jgmelber commented
@fifield can you check if this is ready to merge?

2024-04-17 16:10 UTC, fifield approved these changes

2024-04-17 16:10 UTC, merged