Convert arith.select to aievec.sel for different input data types.
Xilinx/mlir-aie pull request #502
Opened 2023-05-24 16:34 UTC by linay-xsj

2023-05-24 21:02 UTC, david-vc requested changes
HI @linay-xsj 
Can you please also add a test case with compare + select (like i16xi16_sel where the arith.cmpi has ult as predicate.) I think that it is important to show that we are generating correct C code also for this case.

2023-05-24 23:20 UTC, linay-xsj commented
> HI @linay-xsj Can you please also add a test case with compare + select (like i16xi16_sel where the arith.cmpi has ult as predicate.) I think that it is important to show that we are generating correct C code also for this case.

Done.

2023-05-25 01:02 UTC, david-vc reviewed
Thanks for adding the unsigned comparison + select test.
I have a minor request to refactor the code to build the name of a vector type given the element type and lane count.

2023-05-25 01:02 UTC, david-vc commented on lib/Targets/AIEVecToCpp/TranslateAIEVecToCpp.cpp
> +  if (eltType.isa<IntegerType>() &&
Slight variants of  piece of code 1758-1772 appears already multiple times in this file and so it should be refactored.

2023-05-25 01:02 UTC, david-vc reviewed
Thanks for adding the unsigned comparison + select test.
I have a minor request to refactor the code to build the name of a vector type given the element type and lane count.

2023-05-25 16:25 UTC, david-vc approved these changes

2023-05-25 16:32 UTC, merged

2023-05-25 16:42 UTC, keryell commented on lib/Targets/AIEVecToCpp/TranslateAIEVecToCpp.cpp
> +    os << "v" << std::to_string(lanes) << "uint" << std::to_string(width);
It sounds surprising that the streams do not accept directly integers.

2023-05-25 16:42 UTC, keryell commented on include/aie/Dialect/AIEVec/IR/AIEVecOps.td
> +    Xilinx-specific intrinsic that performs lane wise selection between two input vectors, if a bit of sel is zero, the lane of vector lhs is selected, else the lane of vector rhs is selected.
Replacing Xilinx by AMD in new code?

2023-05-25 16:42 UTC, keryell commented on test/unit_tests/aievec_tests/bf16xbf16_sel/defines.h
> +#define OUT0_SIZE 1024
Any reason for not using `constexpr` variables?

2023-05-25 16:42 UTC, keryell commented on test/unit_tests/aievec_tests/bf16xbf16_sel/testbench.cc
> +                [&]() mutable { return random_bfloat16(-10, 10, 2); });
Unclear to me why this is `mutable`.

2023-05-25 16:42 UTC, keryell commented on test/unit_tests/aievec_tests/floatxfloat_sel/defines.h
> +#define IN0_SIZE 1024
https://github.com/isocpp/CppCoreGuidelines/blob/master/CppCoreGuidelines.md#es31-dont-use-macros-for-constants-or-functions